package com.travel.communication.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "USER_DATA".
 */
public class UserData implements Serializable{

    /** Not-null value. */
    private String id;
    /** Not-null value. */
    private String nickName;
    private String imgUrl;

    private String mobile;
    private int sex;
    private String myIntroduction;
    private String userType;
    private String place;

    public UserData() {
    }

    public UserData(String id) {
        this.id = id;
    }

    public UserData(String id, String nickName, String imgUrl) {
        this.id = id;
        this.nickName = nickName;
        this.imgUrl = imgUrl;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNickName() {
        return nickName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public int getSex() {
        return sex;
    }

    public void setSex(int sex) {
        this.sex = sex;
    }

    public String getMyIntroduction() {
        return myIntroduction;
    }

    public void setMyIntroduction(String myIntroduction) {
        this.myIntroduction = myIntroduction;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getPlace() {
        return place;
    }

    public void setPlace(String place) {
        this.place = place;
    }
}
