package com.travel.localfile.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.text.TextUtils;

import com.travel.lib.utils.DateFormatUtil;
import com.travel.localfile.CameraFragment;

import java.io.Serializable;
import java.util.Date;

/**
 * Entity mapped to table "LOCAL_FILE".
 */
public class LocalFile implements Serializable{

    private Long id;
    private String userId;
    private String fileName;
    private String localPath;
    private String remotePath;
    private String thumbnailPath;
    private String orderId;
    private Integer type;
    private Long createTime;
    private String createTimeFormat;
    private String address;
    private String longitudeLatitude;
    private Boolean isUpLoaded = false;
    private Long duration;
    private String durationFormat;
    private String others;
    private Serializable tag;
    private int position;// 在多媒体的数据中所占的位置

    public Serializable getTag() {
        return tag;
    }

    public void setTag(Serializable tag) {
        this.tag = tag;
    }

    public LocalFile() {
    }

    public LocalFile(Long id) {
        this.id = id;
    }

    public LocalFile(Long id, String userId, String fileName, String localPath, String remotePath, String thumbnailPath, String orderId, Integer type, Long createTime, String address, String longitudeLatitude, Boolean isUpLoaded, Long duration, String others) {
        this.id = id;
        this.userId = userId;
        this.fileName = fileName;
        this.localPath = localPath;
        this.remotePath = remotePath;
        this.thumbnailPath = thumbnailPath;
        this.orderId = orderId;
        this.type = type;
        this.createTime = createTime;
        this.createTimeFormat = DateFormatUtil.formatTime(new Date(createTime), DateFormatUtil.FORMAT_DTAE_TIME_ZH_CN);
        this.address = address;
        this.longitudeLatitude = longitudeLatitude;
        this.isUpLoaded = isUpLoaded;
        this.duration = duration;
        this.durationFormat = DateFormatUtil.longToStringByhhmmss(duration/1000);
        this.others = others;
    }

    @Override
    public boolean equals(Object o) {
        if(o == this) return true;
        if(o instanceof LocalFile){
            LocalFile localFile = (LocalFile) o;
            if(getType() == CameraFragment.TYPE_LIVE){
                return !TextUtils.isEmpty(remotePath)
                        && remotePath.equals(localFile.getRemotePath());
            }
            return id.equals(localFile.getId())
                    && !TextUtils.isEmpty(localPath)
                    && localPath.equals(localFile.getLocalPath());
        }else{
            return false;
        }
    }

    @Override
    public int hashCode() {
        if(getType() == CameraFragment.TYPE_LIVE){
            return remotePath.hashCode();
        }
        return (int) (localPath.hashCode() + 37 * id);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getLocalPath() {
        return localPath;
    }

    public void setLocalPath(String localPath) {
        this.localPath = localPath;
    }

    public String getRemotePath() {
        return remotePath;
    }

    public void setRemotePath(String remotePath) {
        this.remotePath = remotePath;
    }

    public String getThumbnailPath() {
        return thumbnailPath;
    }

    public void setThumbnailPath(String thumbnailPath) {
        this.thumbnailPath = thumbnailPath;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
        this.setCreateTimeFormat(DateFormatUtil.formatTime(new Date(createTime), DateFormatUtil.FORMAT_DTAE_TIME_ZH_CN));
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getLongitudeLatitude() {
        return longitudeLatitude;
    }

    public void setLongitudeLatitude(String longitudeLatitude) {
        this.longitudeLatitude = longitudeLatitude;
    }

    public Boolean getIsUpLoaded() {
        return isUpLoaded;
    }

    public void setIsUpLoaded(Boolean isUpLoaded) {
        this.isUpLoaded = isUpLoaded;
    }

    public Long getDuration() {
        return duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
        this.setDurationFormat(DateFormatUtil.longToStringByhhmmss(duration/1000));
    }

    public String getCreateTimeFormat() {
        return createTimeFormat;
    }

    public void setCreateTimeFormat(String createTimeFormat) {
        this.createTimeFormat = createTimeFormat;
    }

    public String getDurationFormat() {
        return durationFormat;
    }

    public void setDurationFormat(String durationFormat) {
        this.durationFormat = durationFormat;
    }

    public String getOthers() {
        return others;
    }

    public void setOthers(String others) {
        this.others = others;
    }

    public int getPosition() {
        return position;
    }

    public void setPosition(int position) {
        this.position = position;
    }
}
